config/routes.rb
Rails.application.routes.draw do
  
  resources :stories do
    resources :votes do
    end
  end
  
  resource :session
  
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates :name, :link, presence:true
  has_many :votes do
    def latest
      order('id DESC').limit(3)
    end
  end

  def to_param
    "#{id}-#{name.gsub(/\W/,'-').downcase}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :stories
  has_many :votes
end
     

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  
  protected
  def current_user
    return unless session[:user_id]
    #@current_user = User.where(id: session[:user_id]).first
    puts "I am current user"
    @current_user = User.find_by(id: session[:user_id])
  end

  def logged_in?
    !@current_user.nil?
  end

  def ensure_login
    return true if logged_in?
    session[:return_to] = fullpath.request
    redirect_to new_session_path and return false
  end

  helper_method :logged_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_user = User.find_by(email: params[:email])
    if 
      @current_user && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      redirect_to stories_path
    else
      render action: 'new'
    end
  end
  def destroy
    session[:user_id] = @current_user = nil
    redirect_to stories_path
  end

  before_action :ensure_login, only: [:new, :create]
  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    #@story = Story.order('RANDOM()').first
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      flash[:notice] = "Story submission succeeded"
      redirect_to stories_path
    else
      render action:'new'
    end  
  end

  def show
    @story = Story.find(params[:id])
  end

  private
  def story_params
    params.require(:story).permit(:name,:link)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @story.votes.create
    respond_to do |format|
      format.html{redirect_to story_path(@story),notice:'Vote was successfully created'}
      format.js{}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dudeit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <div id="content">
    <div id="login_logout">
    <% if @current_user %>
        Logged in as:
        <%= @current_user.name %>
        <em><%= link_to "(Logout)", session_path, data: { "turbo-method": :delete } %></em>
    <% else %>
        <em>Not logged in.</em>
        <%= link_to 'Login', new_session_path %>
    <% end %>
  </div>  

  <body>
  <div id="content"> 
      <h1>Dudeit</h1>
      <% unless flash[:notice].blank? %>
        <div id="notification"> <%= flash[:notice] %> </div>
      <% end %>
    <%= yield %>
    <ul id="navigation">
      <li><%= link_to 'List of stories', stories_path %></li>
      <li><%= link_to 'Submit a new story', new_story_path %></li>
    </ul>
  </body>
</html>

app/views/stories/index.html.erb
<h1>List of Stories</h1>

<table border="1" width="500">
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>Details</th>
    </tr>

  <tbody>
    <% for story in @stories do %>
      <tr>
          <td><%= story.name %></td>
          <td><%= story.link %></td>
          <td><%= link_to story.name, story_path(story) %></td> 
        <% end %>  
      </tr> 
  </tbody>
</table>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
<div class="form_errors" >
  <h3>Errors</h3>
  <ul>
    <% @story.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
</div>
 <% end %> 
<%= form_for @story, data: {turbo:false} do |f| %>
  <div>
    <p>
    <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
  </div>

  <div>
    <p>
      <%= f.label :link %>
      <%= f.text_field :link %>
    </p>
  </div>
  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
  <ul id="vote_history">
    <% if @story.votes.empty? %>
      <em> No votes yet! </em>
    <% else %>
      <%= render partial: "votes/vote" , collection: @story.votes.latest %>
    <% end %>
  </ul>
<h2>Name of the story: <%= @story.name %></h2>
<p><%= link_to @story.link, @story.link %></p><br>

<div id="vote_form">
  <%= form_tag(story_votes_path(@story),remote: true) do%>
    <%= submit_tag 'Vote For It'%>
  <% end %> 
</div>
<h2>
  <span id="vote_score">
      Score:<%= @story.votes.count %>
  </span>
</h2>

app/views/votes/_vote.html.erb
<li><%= vote.created_at.to_formatted_s(:short) %></li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>